
name = "Ananke / Ferruccio Gohugo Theme"
license = "MIT"
licenselink = "https://github.com/budparr/gohugo-theme-ananke/blob/master/LICENSE.md"
description = "A Base theme for building full featured Hugo sites"
features = ["posts", "shortcodes", "related content", "comments"]

[author]
  name = "Bud Parr"
  homepage = "https://github.com/budparr"
