
name = "Ferruccio Gohugo Theme"
license = "MIT"
licenselink = "https://github.com/ferrucc-io/ferruccio-theme/blob/master/LICENSE.md"
description = "A Base theme for building full featured Hugo sites"
features = ["posts", "shortcodes", "related content", "comments"]

[author]
  name = "Ferruccio Balestreri"
  homepage = "https://github.com/ferrucc-io"
